'use client';

import { Printer, ArrowLeft, Building2 } from 'lucide-react';
import NextLink from 'next/link';
import { Button } from '@/components/ui/button';

export default function ImpactReportView({ data }: { data: any }) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-[#0B1120] text-slate-50 print:bg-white print:text-black font-sans">
      {/* Non-printable header */}
      <div className="print:hidden border-b border-white/[0.06] bg-[#0B1120]/80 backdrop-blur-xl p-4 flex justify-between items-center sticky top-0 z-40">
        <NextLink href="/official" className="flex items-center gap-2 text-slate-400 hover:text-teal-400 transition-colors text-sm font-medium">
          <ArrowLeft size={18} /> Back to Command Center
        </NextLink>
        <Button onClick={handlePrint} className="civic-gradient hover:opacity-90 text-white gap-2 border-0 shadow-lg shadow-teal-500/20 rounded-xl transition-all active:scale-[0.98]">
          <Printer size={16} /> Download as PDF
        </Button>
      </div>

      {/* Printable Report Content */}
      <div className="max-w-4xl mx-auto p-10 print:p-0 bg-white text-slate-900 shadow-2xl my-8 print:my-0 print:shadow-none min-h-[1056px] rounded-3xl print:rounded-none">
        {/* Report Header */}
        <div className="border-b-4 border-[#0F766E] pb-6 mb-8 flex justify-between items-end">
          <div>
            <div className="flex items-center gap-3 text-[#0F766E] mb-2">
              <Building2 size={36} />
              <h1 className="text-4xl font-extrabold tracking-tight text-slate-900">Municipal Impact Report</h1>
            </div>
            <p className="text-slate-500 font-medium tracking-wide uppercase text-sm">City of {data.city || 'Metropolis'}</p>
          </div>
          <div className="text-right">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Generated By</p>
            <p className="font-bold text-slate-800">{data.officialName}</p>
            <p className="text-sm text-slate-500 font-mono mt-0.5">{new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
        </div>

        {/* Executive Summary (AI Generated) */}
        <div className="mb-10">
          <h2 className="text-sm font-bold uppercase tracking-widest text-[#0F766E] border-b border-slate-200 pb-2 mb-4">Executive Summary</h2>
          <div className="bg-slate-50/50 border-l-4 border-[#0F766E] p-6 rounded-r-2xl">
            <p className="text-lg leading-relaxed text-slate-700">
              {data.narrative}
            </p>
          </div>
        </div>

        {/* Key Metrics */}
        <div className="mb-10">
          <h2 className="text-sm font-bold uppercase tracking-widest text-[#0F766E] border-b border-slate-200 pb-2 mb-4">Key Performance Metrics</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="border border-slate-200 rounded-2xl p-6 text-center bg-white shadow-sm">
              <p className="text-5xl font-extrabold text-slate-900 mb-2">{data.total}</p>
              <p className="text-xs uppercase font-bold tracking-widest text-slate-500">Total Reports</p>
            </div>
            <div className="border border-[#14B8A6]/30 rounded-2xl p-6 text-center bg-teal-50/50 shadow-sm">
              <p className="text-5xl font-extrabold text-[#0F766E] mb-2">{data.resolved}</p>
              <p className="text-xs uppercase font-bold tracking-widest text-[#0F766E]">Resolved</p>
            </div>
            <div className="border border-[#D97706]/30 rounded-2xl p-6 text-center bg-amber-50/50 shadow-sm">
              <p className="text-5xl font-extrabold text-[#D97706] mb-2">{data.duplicates}</p>
              <p className="text-xs uppercase font-bold tracking-widest text-[#D97706]">Duplicates Blocked</p>
            </div>
            <div className="border border-[#EA580C]/30 rounded-2xl p-6 text-center bg-orange-50/50 shadow-sm">
              <p className="text-5xl font-extrabold text-[#EA580C] mb-2">{data.emergency}</p>
              <p className="text-xs uppercase font-bold tracking-widest text-[#EA580C]">Emergencies</p>
            </div>
          </div>
        </div>

        {/* Efficiency Calculation */}
        <div className="mb-10">
          <h2 className="text-sm font-bold uppercase tracking-widest text-[#0F766E] border-b border-slate-200 pb-2 mb-4">Resource Efficiency</h2>
          <div className="border border-slate-200 rounded-2xl overflow-hidden">
            <table className="w-full text-left border-collapse">
              <tbody>
                <tr className="border-b border-slate-100 bg-white">
                  <td className="py-4 px-6 font-medium text-slate-600">Estimated Manual Triage Time Saved</td>
                  <td className="py-4 px-6 font-bold text-right text-slate-900">{Math.round(data.total * 0.25)} hours</td>
                </tr>
                <tr className="border-b border-slate-100 bg-white">
                  <td className="py-4 px-6 font-medium text-slate-600">Estimated Duplicate Labor Prevented</td>
                  <td className="py-4 px-6 font-bold text-right text-slate-900">{Math.round(data.duplicates * 4.5)} hours</td>
                </tr>
                <tr className="bg-slate-50">
                  <td className="py-5 px-6 font-bold text-lg text-slate-800 uppercase tracking-wider text-sm">Total Labor Hours Reclaimed</td>
                  <td className="py-5 px-6 font-extrabold text-2xl text-right text-[#0F766E]">
                    {Math.round((data.total * 0.25) + (data.duplicates * 4.5))} hrs
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Category Breakdown */}
        <div>
          <h2 className="text-sm font-bold uppercase tracking-widest text-[#0F766E] border-b border-slate-200 pb-2 mb-4">Issue Breakdown</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-x-8 gap-y-4">
            {Object.entries(data.categories).map(([category, count]) => (
              <div key={category} className="flex justify-between items-center border-b border-slate-100 py-2">
                <span className="font-medium text-slate-700 text-sm">{category}</span>
                <span className="font-bold bg-slate-100 px-3 py-1 rounded-full text-xs text-slate-600">{String(count)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-16 pt-6 border-t border-slate-200 flex justify-between items-center text-xs text-slate-400 font-medium uppercase tracking-wider">
          <p>Generated by Nagar Drishti.ai</p>
          <p>Department of Civic Innovation</p>
        </div>
      </div>
    </div>
  );
}
